# TCL File Generated by Component Editor 19.1
# Tue Feb 18 16:43:18 CET 2020
# DO NOT MODIFY


# 
# infrared "infrared" v1.0
# Michael Wurm 2020.02.18.16:43:18
# Infrared Recorder/Transmitter
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module infrared
# 
set_module_property DESCRIPTION "Infrared Recorder/Transmitter"
set_module_property NAME infrared
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Michael Wurm"
set_module_property DISPLAY_NAME infrared
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL infrared
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file counter.vhd VHDL PATH components/infrared/counter.vhd
add_fileset_file infrared.vhd VHDL PATH components/infrared/infrared.vhd TOP_LEVEL_FILE
add_fileset_file sync_single.vhd VHDL PATH components/infrared/sync_single.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clk_i
set_interface_property s0 associatedReset rst_n_i
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 8
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clk_i
# 
add_interface clk_i clock end
set_interface_property clk_i clockRate 0
set_interface_property clk_i ENABLED true
set_interface_property clk_i EXPORT_OF ""
set_interface_property clk_i PORT_NAME_MAP ""
set_interface_property clk_i CMSIS_SVD_VARIABLES ""
set_interface_property clk_i SVD_ADDRESS_GROUP ""

add_interface_port clk_i clk_i clk Input 1


# 
# connection point rst_n_i
# 
add_interface rst_n_i reset end
set_interface_property rst_n_i associatedClock clk_i
set_interface_property rst_n_i synchronousEdges DEASSERT
set_interface_property rst_n_i ENABLED true
set_interface_property rst_n_i EXPORT_OF ""
set_interface_property rst_n_i PORT_NAME_MAP ""
set_interface_property rst_n_i CMSIS_SVD_VARIABLES ""
set_interface_property rst_n_i SVD_ADDRESS_GROUP ""

add_interface_port rst_n_i rst_n_i reset_n Input 1

