# TCL File Generated by Component Editor 19.1
# Thu Feb 20 13:30:47 CET 2020
# DO NOT MODIFY


#
# infrared "infrared" v1.0
# Michael Wurm 2020.02.20.13:30:47
# Infrared Recorder/Transmitter
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module infrared
#
set_module_property DESCRIPTION "Infrared Recorder/Transmitter"
set_module_property NAME infrared
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Michael Wurm"
set_module_property DISPLAY_NAME infrared
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL infrared
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file counter.vhd VHDL PATH counter.vhd
add_fileset_file sync_single.vhd VHDL PATH sync_single.vhd
add_fileset_file infrared.vhd VHDL PATH infrared.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file counter.vhd VHDL PATH counter.vhd
add_fileset_file sync_single.vhd VHDL PATH sync_single.vhd
add_fileset_file infrared.vhd VHDL PATH infrared.vhd


#
# parameters
#


#
# module assignments
#
set_module_assignment embeddedsw.dts.group sensor
set_module_assignment embeddedsw.dts.name infrared
set_module_assignment embeddedsw.dts.vendor wur


#
# display items
#


#
# connection point s0
#
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clk_i
set_interface_property s0 associatedReset rst_n_i
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 8
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


#
# connection point clk_i
#
add_interface clk_i clock end
set_interface_property clk_i clockRate 0
set_interface_property clk_i ENABLED true
set_interface_property clk_i EXPORT_OF ""
set_interface_property clk_i PORT_NAME_MAP ""
set_interface_property clk_i CMSIS_SVD_VARIABLES ""
set_interface_property clk_i SVD_ADDRESS_GROUP ""

add_interface_port clk_i clk_i clk Input 1


#
# connection point rst_n_i
#
add_interface rst_n_i reset end
set_interface_property rst_n_i associatedClock clk_i
set_interface_property rst_n_i synchronousEdges DEASSERT
set_interface_property rst_n_i ENABLED true
set_interface_property rst_n_i EXPORT_OF ""
set_interface_property rst_n_i PORT_NAME_MAP ""
set_interface_property rst_n_i CMSIS_SVD_VARIABLES ""
set_interface_property rst_n_i SVD_ADDRESS_GROUP ""

add_interface_port rst_n_i rst_n_i reset_n Input 1


#
# connection point done_recording_irq
#
add_interface done_recording_irq interrupt end
set_interface_property done_recording_irq associatedAddressablePoint ""
set_interface_property done_recording_irq associatedClock clk_i
set_interface_property done_recording_irq associatedReset rst_n_i
set_interface_property done_recording_irq bridgedReceiverOffset ""
set_interface_property done_recording_irq bridgesToReceiver ""
set_interface_property done_recording_irq ENABLED true
set_interface_property done_recording_irq EXPORT_OF ""
set_interface_property done_recording_irq PORT_NAME_MAP ""
set_interface_property done_recording_irq CMSIS_SVD_VARIABLES ""
set_interface_property done_recording_irq SVD_ADDRESS_GROUP ""

add_interface_port done_recording_irq done_recording_irq_o irq Output 1


#
# connection point ir_rx_i
#
add_interface ir_rx_i conduit end
set_interface_property ir_rx_i associatedClock clk_i
set_interface_property ir_rx_i associatedReset ""
set_interface_property ir_rx_i ENABLED true
set_interface_property ir_rx_i EXPORT_OF ""
set_interface_property ir_rx_i PORT_NAME_MAP ""
set_interface_property ir_rx_i CMSIS_SVD_VARIABLES ""
set_interface_property ir_rx_i SVD_ADDRESS_GROUP ""

add_interface_port ir_rx_i ir_rx_i conduit Input 1


#
# connection point ir_rx_o
#
add_interface ir_rx_o conduit end
set_interface_property ir_rx_o associatedClock clk_i
set_interface_property ir_rx_o associatedReset ""
set_interface_property ir_rx_o ENABLED true
set_interface_property ir_rx_o EXPORT_OF ""
set_interface_property ir_rx_o PORT_NAME_MAP ""
set_interface_property ir_rx_o CMSIS_SVD_VARIABLES ""
set_interface_property ir_rx_o SVD_ADDRESS_GROUP ""

add_interface_port ir_rx_o ir_rx_o conduit Output 1


#
# connection point ir_tx_o
#
add_interface ir_tx_o conduit end
set_interface_property ir_tx_o associatedClock clk_i
set_interface_property ir_tx_o associatedReset ""
set_interface_property ir_tx_o ENABLED true
set_interface_property ir_tx_o EXPORT_OF ""
set_interface_property ir_tx_o PORT_NAME_MAP ""
set_interface_property ir_tx_o CMSIS_SVD_VARIABLES ""
set_interface_property ir_tx_o SVD_ADDRESS_GROUP ""

add_interface_port ir_tx_o ir_tx_o conduit Output 1

